id: I8D8DF4D4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T14:45:49+00:00'
last_modified: '2022-06-09T17:43:02.437218+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15846
  title: ཀུན་མཁྱེན་པདྨ་དཀར་པོའི་རྣམ་ཐར་སྙན་ངག་ཅན་གྱི་འགྲེལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BDC:
      image_group_id: I1KG15848
      title: Volume 1 of kun mkhyen pad+ma dkar po'i rnam thar snyan ngag can gyi
        'grel ba/
      total_pages: 98
      order: 1
      base_file: 9BDC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
